### PR TITLE
feat: Update to Backstage 1.25.0

### LINKED ISSUE #39: chore: Update repository to Backstage 1.24.0
Upgrade the repository to 1.24.0.

- [ ] Follow Backstage upgrade process https://backstage.io/docs/getting-started/keeping-backstage-updated/
- [ ] Make sure Backstage app is using the new backend system, since this is the default going forwards
- [ ] Ensure all plugins work with new backend system

### PR DESCRIPTION
**Pull request by drodil**
closes #39

### Reason for this change

New backend system in use for local development

### Description of changes

Removed all old backend things
Replaced the packages/backend with the new backend system

### Description of how you validated changes

Local testing

### Checklist

- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

---

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license_

### CODE REVIEW

**Comment by sheershoff** [comment]
Is there a plan to also update obviously deprecated installation instructions? :-)

**Comment by drodil** [comment]
Good point 😅 Maybe should do that as well.

**Comment by niallthomson** [comment]
Thanks @drodil this is a really helpful PR! Let me take some time to look it over and test it.

**Comment by niallthomson** [comment]
Should we update the [scaffolder package](https://github.com/awslabs/backstage-plugins-for-aws/tree/main/plugins/core/scaffolder-actions) so it declares a module properly and exports it?

**Comment by drodil** [comment]
@niallthomson yes we should. Just didn't have time to do it yesterday and could also be done in a separate PR.

**Comment by drodil** [comment]
@niallthomson sure thing! I am off for easter vacation so if you want to get this merged, please add your fixes 🤗

**Comment by niallthomson** [comment]
Enjoy your vacation!

**Pull request merged**
