### PR TITLE
fix: export plugins as default for new backstage backend

### PR DESCRIPTION
**Pull request by drodil**
### Reason for this change

To make these plugins work with the new Backstage backend system

### Description of changes

Export plugin as default from index.ts

### Description of how you validated changes

No need

### Checklist

- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

---

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license_

### CODE REVIEW

**Comment by niallthomson** [comment]
Thanks @drodil . Have you noticed any other incompatibilities with the new backend system so far? We have an outstanding task to test it now that its the default with 1.24.

**Comment by drodil** [comment]
Haven't seen many incompatibilities. Some bugs were introduced in 1.24.0/1/2, but hopefully there will be one more patch today. Some custom features are impossible to implement with the new backend system, but hopefully they will open a bit in the future. What comes to plugins and maintaining them, it's much easier. 

Waiting for this PR to get in to get also these plugins working with the new backend 👌

**Review by niallthomson — APPROVED** [review]
LGTM

**Comment by drodil** [comment]
Any chance to get a release? Thanks!

**Comment by niallthomson** [comment]
Just pushed a release, sorry for the delay.

**Pull request merged**
