### PR TITLE
feat: Add support for IAM Identity Center shortcut links

### LINKED ISSUE #87: feature: Support for IAM Identity Center shortcut links
### 🔖 Feature description

There are already situations where we provide deep links to specific screens within the AWS console from Backstage plugins, such as the specific CodePipeline executions or CodeBuild project builds. It is expected that we will continue to add more of these in the interest of avoiding re-producing all AWS console information in Backstage. 

However providing these deep links to the AWS console can be tricky in a situation where multiple AWS accounts are involved since the console does not have a mechanism to switch accounts. This means the existing links will not properly account for cross-account situations where the user is not logged in to the appropriate account.

The new shortcut link feature for IAM Identity Center lets you construct links via the access portal that point to specific AWS accounts. This would at least allow users leveraging Identity Center to provide better link capabilities in their Backstage portal.

### 🎤 Context

Shortcut links documentation:

https://aws.amazon.com/about-aws/whats-new/2024/04/aws-iam-identity-center-shortcut-links-aws-access-portal/

### ✌️ Possible Implementation

This feature would need to be optional and probably packaged as a utility function in a core package.

To construct a link with this feature it would need to be aware of the Identity Center portal domain (for example `your_subdomain.awsapps.com`) and parameters would be the target account ID and full link to the particular screen in the AWS console (for example `https://us-west-2.console.aws.amazon.com/s3/buckets/my-bucket-name`).

### PR DESCRIPTION
**Pull request by benjidotsh**
### Issue # (if applicable)

Closes #87 

### Reason for this change

Adds support for IAM Identity Center shortcut links.

### Description of changes

Added an `aws.sso.subdomain` config parameter that, if provided, generates an IAM Identity Center shortcut link using the provided subdomain

### Description of how you validated changes

Inspected and thoroughly tested the newly generated links.

### Checklist

- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

---

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license_

### CODE REVIEW

**Comment by niallthomson** [comment]
Hey @benjidotsh thanks for taking a swing at this one!

Couple of initial thoughts looking through the code:

1. It feels like this should live in the `react` package since its strictly related to the front-end, thoughts?
2. We already parse ARNs elsewhere with a standard library, see [here](https://github.com/awslabs/backstage-plugins-for-aws/blob/main/plugins/codepipeline/backend/src/service/DefaultAwsCodePipelineService.ts#L101)
3. I see the `config.d.ts` added in the CodePipeline package, but there isn't one in the CodeBuild package. I'm not familiar enough with the plugin config stuff to know if this is how we should be going about it. It feels like it should be in one shared place or everywhere?

**Comment by benjidotsh** [comment]
@niallthomson you're welcome!

1. What specific code do you mean? The utils? The reason I put them in the common package is because I thought they were pretty domain-agnostic and could theoretically be used in the backend in the future as well. I understand why you would put them in the react package though!
2. Oops, I did look for something like this in the code, but not good enough I guess 😄
3. Good point, I missed that. I'm not too familiar with plugin config either since this is the first time I take a stab at it.

I'll look into it on Tuesday!

**Comment by benjidotsh** [comment]
I have replaced my `parseArn` function with the standard `parse` function and added the `config.d.ts` to the CodeBuild plugin as well.

Let me know your thoughts on the first point and I'll make the necessary changes. 😄

**Comment by niallthomson** [comment]
Thanks for the change to the parse. Let me read up a bit on the config stuff today.

I think we can leave this in common since perhaps it will be used in a backend.

**Comment by niallthomson** [comment]
Sorry for the slow response on this one, testing this today

**Comment by benjidotsh** [comment]
@niallthomson no worries, thanks for the update!

**Comment by niallthomson** [comment]
Thanks for implementing this @benjidotsh I just added some basic tests.

**Pull request merged**
